### ISSUE TITLE
Add projects

### ISSUE THREAD

**Issue by dceluis** [sanchez2210/durt#1]
Projects / workspaces (choose wording), encapsulate a bug tracker and a time tracker.

Issues belong to project, and statuses also belong to project.
Each project should have a configuration area on .durt.yml

Example: 

```
projects:
  -
      name: 'Project 1'
      bug_tracker:
        key: 'github'
        config:
          username: 43435@asdf.com
          #....
      time_tracker: 'sth'

 -
    name 'Project 2'
    bug_tracker:
      key: 'Jira'
      config:
        username: 234234
    time_tracker: 'another sth'

```
